# Generated by Django 3.2.7 on 2021-09-15 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
