# Generated by Django 3.2.7 on 2021-09-15 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='users_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
